# Generated by Django 5.1.4 on 2025-01-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(max_length=30, null=True)),
                ('Uemail', models.EmailField(max_length=254)),
                ('Uphone', models.BigIntegerField()),
                ('Uaddress', models.TextField()),
                ('Upassword', models.CharField(max_length=8, null=True)),
            ],
        ),
    ]
