# Generated by Django 5.1.4 on 2025-01-05 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registermodel',
            old_name='Uaddress',
            new_name='u_address',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='Uemail',
            new_name='u_email',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='Uname',
            new_name='u_name',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='Upassword',
            new_name='u_password',
        ),
        migrations.RenameField(
            model_name='registermodel',
            old_name='Uphone',
            new_name='u_phone',
        ),
    ]
