# Generated by Django 5.1.6 on 2025-02-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0002_rename_uaddress_registermodel_u_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='id_proof',
            field=models.FileField(blank=True, default=None, null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('User', 'User')], default='User', max_length=10),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='status',
            field=models.CharField(choices=[('0', 'unapproved'), ('1', 'approved')], default='0', max_length=10),
        ),
    ]
