# Generated by Django 5.1.4 on 2025-02-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0003_registermodel_id_proof_registermodel_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='Profile',
            field=models.FileField(blank=True, default=None, null=True, upload_to='id_proofs/'),
        ),
    ]
