# Generated by Django 5.1.4 on 2025-02-23 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0004_registermodel_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registermodel',
            old_name='Profile',
            new_name='profile',
        ),
    ]
