# Generated by Django 5.1.4 on 2025-02-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0005_rename_profile_registermodel_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='cars_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_img', models.ImageField(blank=True, default=None, null=True, upload_to='Cars/')),
                ('v_name', models.TextField()),
                ('seats', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=20)),
                ('VIN', models.BigIntegerField()),
                ('AEC', models.TextField()),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('0', 'Unavailable'), ('1', 'Available')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='registermodel',
            name='profile',
        ),
    ]
