# Generated by Django 5.1.4 on 2025-02-24 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0006_cars_img_remove_registermodel_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cars_img',
            new_name='cars',
        ),
    ]
