# Generated by Django 5.1.4 on 2025-02-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0007_rename_cars_img_cars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='v_img',
            new_name='vehicle_image',
        ),
    ]
