# Generated by Django 5.1.4 on 2025-02-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0008_rename_v_img_cars_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='seats',
            field=models.CharField(choices=[('4', '4'), ('5', '5'), ('7', '7')], max_length=10),
        ),
    ]
