# Generated by Django 5.1.4 on 2025-02-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0009_alter_cars_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='seats',
            field=models.CharField(choices=[('0', '4'), ('1', '5'), ('2', '7')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cars',
            name='vehicle_type',
            field=models.CharField(choices=[('0', 'SUVs'), ('1', 'Sedans'), ('2', 'Crossovers'), ('3', 'Coupes'), ('4', 'Hatchbacks')], max_length=20),
        ),
    ]
