# Generated by Django 5.1.4 on 2025-02-24 14:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0010_alter_cars_seats_alter_cars_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='maintenancemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_health', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=100)),
                ('charging_history', models.TextField()),
                ('mileage', models.IntegerField()),
                ('tire_condition', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Worn', 'Worn'), ('Replace', 'Replace')], max_length=100)),
                ('brake_system', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=100)),
                ('service_history', models.TextField()),
                ('inspection_date', models.DateField(default=datetime.date.today)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RVApp.cars')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RVApp.registermodel')),
            ],
        ),
    ]
