# Generated by Django 5.1.4 on 2025-02-25 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0011_maintenancemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cars',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RVApp.category'),
        ),
    ]
