# Generated by Django 5.1.4 on 2025-02-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0012_category_alter_cars_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='vehicle_type',
            field=models.CharField(choices=[('0', 'SUVs'), ('1', 'Sedans'), ('2', 'Crossovers'), ('3', 'Coupes'), ('4', 'Hatchbacks')], max_length=20),
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
