# Generated by Django 5.1.4 on 2025-02-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0014_bookingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='vehicle_image',
            field=models.ImageField(blank=True, default=None, upload_to='Cars/'),
        ),
    ]
