# Generated by Django 5.1.4 on 2025-02-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0015_alter_cars_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='vehicle_image',
            field=models.ImageField(default=None, upload_to='Cars/'),
        ),
    ]
