# Generated by Django 5.1.4 on 2025-02-27 03:54

import RVApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0018_alter_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='AEC',
        ),
        migrations.AddField(
            model_name='cars',
            name='color',
            field=models.CharField(default='White', max_length=20),
        ),
        migrations.AddField(
            model_name='cars',
            name='doors',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='cars',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cars',
            name='stock_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cars',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='drop_loc',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='pickup_loc',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='rental_date',
            field=models.DateField(default=RVApp.models.current_date),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='return_date',
            field=models.DateField(default=RVApp.models.current_date),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cars',
            name='VIN',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cars',
            name='seats',
            field=models.CharField(choices=[('0', '4'), ('1', '5'), ('2', '7')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='cars',
            name='status',
            field=models.CharField(choices=[('0', 'Unavailable'), ('1', 'Available')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='cars',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='Cars/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='vehicle_type',
            field=models.CharField(choices=[('0', 'SUVs'), ('1', 'Sedans'), ('2', 'Crossovers'), ('3', 'Coupes'), ('4', 'Hatchbacks')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancemodel',
            name='battery_health',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='Good', max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenancemodel',
            name='brake_system',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='Good', max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenancemodel',
            name='charging_history',
            field=models.TextField(default='No records yet'),
        ),
        migrations.AlterField(
            model_name='maintenancemodel',
            name='inspection_date',
            field=models.DateField(default=RVApp.models.current_date),
        ),
        migrations.AlterField(
            model_name='maintenancemodel',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maintenancemodel',
            name='service_history',
            field=models.TextField(default='No service history'),
        ),
        migrations.AlterField(
            model_name='maintenancemodel',
            name='tire_condition',
            field=models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Worn', 'Worn'), ('Replace', 'Replace')], default='Good', max_length=100),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
    ]
