# Generated by Django 5.1.4 on 2025-02-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0019_remove_cars_aec_cars_color_cars_doors_cars_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='vehicle_type',
            field=models.CharField(choices=[('SUVs', 'SUVs'), ('Sedans', 'Sedans'), ('Crossovers', 'Crossovers'), ('Coupes', 'Coupes'), ('Hatchbacks', 'Hatchbacks')], default='1', max_length=20),
        ),
    ]
