# Generated by Django 5.1.4 on 2025-02-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0020_alter_cars_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='doors',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='stock_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.IntegerField(),
        ),
    ]
