# Generated by Django 5.1.4 on 2025-02-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0021_alter_cars_doors_alter_cars_stock_no_alter_cars_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='color',
            field=models.CharField(max_length=20),
        ),
    ]
