# Generated by Django 5.0.6 on 2025-03-06 05:21

import RVApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0022_alter_cars_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='Cars/')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField(default=RVApp.models.current_date)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
