# Generated by Django 5.0.6 on 2025-03-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0023_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
