# Generated by Django 5.0.6 on 2025-03-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0024_cars_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='make',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='model',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
