# Generated by Django 5.0.6 on 2025-03-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0025_cars_make_cars_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='model',
        ),
    ]
