# Generated by Django 5.0.6 on 2025-03-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0026_remove_cars_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='stock_no',
            field=models.CharField(max_length=30),
        ),
    ]
