# Generated by Django 5.0.6 on 2025-03-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0028_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_img', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('g_name', models.TextField()),
            ],
        ),
    ]
