# Generated by Django 5.0.6 on 2025-03-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0029_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
        migrations.AlterField(
            model_name='cars',
            name='VIN',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cars',
            name='make',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='stock_no',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='vehicle_type',
            field=models.CharField(choices=[('SUVs', 'SUVs'), ('Sedans', 'Sedans'), ('Crossovers', 'Crossovers'), ('Coupes', 'Coupes'), ('Hatchbacks', 'Hatchbacks')], default='1', max_length=50),
        ),
    ]
