# Generated by Django 5.0.6 on 2025-03-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0030_delete_blog_alter_cars_vin_alter_cars_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='u_email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
