# Generated by Django 5.1.4 on 2025-04-04 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0032_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RVApp.bookingmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RVApp.registermodel')),
                ('vehicleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RVApp.cars')),
            ],
        ),
    ]
