# Generated by Django 5.1.4 on 2025-04-04 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RVApp', '0033_feedreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedreview',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RVApp.bookingmodel'),
        ),
    ]
